// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPcyUuPxhmUnLQr79TOwpseVKQr82Vm4',
    appId: '1:582131524226:web:fb2d5ba6cdef9b836bca9b',
    messagingSenderId: '582131524226',
    projectId: 'pribumi-app-d4eca',
    authDomain: 'pribumi-app-d4eca.firebaseapp.com',
    storageBucket: 'pribumi-app-d4eca.appspot.com',
    measurementId: 'G-JCDH3JZMRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVQS13rn5dQqMQBnX7jsD0jJBlBJiVsY',
    appId: '1:582131524226:android:c6bf4055053f92dd6bca9b',
    messagingSenderId: '582131524226',
    projectId: 'pribumi-app-d4eca',
    storageBucket: 'pribumi-app-d4eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOKDdzxgqu4JeY64AYHjtKDQMgHWrZXI',
    appId: '1:582131524226:ios:de77bffb8389a2366bca9b',
    messagingSenderId: '582131524226',
    projectId: 'pribumi-app-d4eca',
    storageBucket: 'pribumi-app-d4eca.appspot.com',
    iosBundleId: 'com.example.pribumiApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxOKDdzxgqu4JeY64AYHjtKDQMgHWrZXI',
    appId: '1:582131524226:ios:0de2502fcae971356bca9b',
    messagingSenderId: '582131524226',
    projectId: 'pribumi-app-d4eca',
    storageBucket: 'pribumi-app-d4eca.appspot.com',
    iosBundleId: 'com.example.pribumiApps.RunnerTests',
  );
}
